db:
  image: library/mysql:5.6.22
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=docker
web:
  image: ootterskog/boot-docker-experiment
  links:
    - db
  volumes:
    - .:/tmp
  ports:
    - "8080:8080"